### ISSUE TITLE
struct bpf_elf_map not supported, coming from future version?

### ISSUE THREAD

**Issue by NobinPegasus** [terassyi/go-xdp-examples#1]
When I try to attach the .o file to an interface I get the following error:
```
pegasus@pegasus:~/Documents/eBPF/go-xdp-examples/xdp_dump$ sudo ./netns.sh attach
struct bpf_elf_map not supported, coming from future version?
Error fixing up map structure, incompatible struct bpf_elf_map used?
Error fetching ELF ancillary data!
```
Here is the attach code: 
```
ip netns exec node1 ip link set dev veth1 xdp obj xdpdump_bpfel.o sec xdp
```

**Comment by terassyi** [comment]
Hi!

Which version of `iproute2`, `clang` and Linux kernel do you use?

**Comment by NobinPegasus** [comment]
```
pegasus@pegasus:~$ clang --version
clang version 19.0.0git (https://github.com/llvm/llvm-project.git 815644b4dd882ade2e5649d4f97c3dd6f7aea200)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/pegasus/Documents/llvm-project/build/bin
```
```
pegasus@pegasus:~$ uname -a
Linux pegasus 6.4.0-060400-generic #202306271339 SMP PREEMPT_DYNAMIC Tue Jun 27 14:26:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

```
pegasus@pegasus:~$ ip -V
ip utility, iproute2-6.1.0, libbpf 1.1.0
```

**Comment by NobinPegasus** [comment]
@terassyi Could you add a tutorial on how to run this codes?
Maybe I'm doing something wrong in the procedure.
What I'm doing is running `go generate` or `go run` from inside of xdp_dump directory.

Then I'm trying to attach the eBPF object to an interface using the following netns.sh

```
#!/bin/bash

BUILD="build"
CLEAN="clean"
ATTACH="attach"
DETACH="detach"
READELF="readelf"

if [ "$BUILD" = "$1" ]; then
	ip netns add node1
	ip link add veth0 type veth peer veth1
	ip link set veth1 netns node1
	ip addr add 192.168.0.3/24 dev veth0
	ip netns exec node1 ip addr add 192.168.0.2/24 dev veth1
	ip link set up dev veth0
	ip netns exec node1 ip link set up dev veth1
	ip netns exec node1 ip link set up dev lo

elif [ "$CLEAN" = "$1" ]; then
	ip netns del node1

elif [ "$ATTACH" = "$1" ]; then
	ip netns exec node1 ip link set dev veth1 xdp obj xdpdump_bpfel.o sec xdp

elif [ "$DETACH" = "$1" ]; then
	ip link set dev eth0 xdp off

elif [ "$READELF" = "$1" ]; then
	readelf -S xdpdump_bpfeb.o

else
	echo "help:"
	echo "	build: build a network to test with netns"
	echo "	clean: clean up a network"
fi
```

First I ran ./netns.sh build. Then
when I run ./netns.sh attach it throws the following error.

**Comment by terassyi** [comment]
Thank you for giving information.

> What I'm doing is running go generate or go run from inside of xdp_dump directory.

What you have to do is to run following commands.

```console
$ cd xdp_dump
$ go generate
$ go build .
$ sudo ./xdp_dump -iface <your NIC name>
# if you want to run into some netns, run below
# sudo ip netns exec <your netns> ./xdp_dump -iface <your NIC name> 
```

`xdpdump_bpfel.o` is generated by running `go generate` , as you did.
This file is used for embedding into `xdpdump_bpfel.go`(This file is also generated by `go generate`).

I use this to generate these files.
https://github.com/cilium/ebpf/tree/main/cmd/bpf2go
To use this, we can generate bpf skeleton code for go and we can run ebpf project as a single go binary.

The document for bpf skeleton is here.
https://docs.kernel.org/bpf/libbpf/libbpf_overview.html#bpf-object-skeleton-file

**Comment by terassyi** [comment]
It is confusing but, `netns.sh` is only for building network namespaces...

> Could you add a tutorial on how to run this codes?

This repository is for my blog post in Japanese.
And I don't plan to write English version, sorry.
https://terassyi.net/posts/2021/10/18/intro-xdp.html

If you want to learn XDP and eBPF now, I recommend reading `Learning eBPF` by Liz Rice.
https://isovalent.com/books/learning-ebpf/

**Comment by NobinPegasus** [comment]
Thanks a lot. You saved a lot of time and hassle for me.
I was able to run xdp_dump and packet_counter. Both with local interface and virtual interface.
But what I'm facing now is while I attach packet_counter to local interface it doesn't work.

```
sudo ./packet_counter -iface enp2s0
```
The code runs but it doesn't count anything
I'm using this command and
After opening another terminal 
I'm pinging enp2s0 address namely 192.168.0.100.
`ping 192.168.0.100`

Could you look into issue?

**Comment by terassyi** [comment]
Thank you for reporting.

Yeah, this program doesn't work well too in my environment...(and I'm not sure why)

To debug this, I modified this like below and ran this.
Then, I could get logs that can count up successfully.
```
diff --git a/packet_counter/bpf/xdp.c b/packet_counter/bpf/xdp.c
index fa525d6..42b2277 100644
--- a/packet_counter/bpf/xdp.c
+++ b/packet_counter/bpf/xdp.c
@@ -60,10 +60,11 @@ int packet_count(struct xdp_md *ctx) {
     __u64 *counter = bpf_map_lookup_elem(&protocols, &proto_index);
     if (counter) {
       (*counter)++;
+         bpf_printk("Count packets: %d: %d", proto_index, *counter);
     }
   }

   return XDP_PASS;
 }

-char _license[] SEC("license") = "GPLv2";
+char _license[] SEC("license") = "Dual BSD/GPL";
```

```console
18:12 zsh ❯ sudo bpftool prog tracelog
            ping-618162  [010] ..s21 3651786.040229: bpf_trace_printk: Count packets: 1: 1
            ping-618162  [010] ..s21 3651787.064292: bpf_trace_printk: Count packets: 1: 2
            ping-618162  [010] ..s21 3651788.088275: bpf_trace_printk: Count packets: 1: 3
            ping-618162  [010] ..s21 3651789.112296: bpf_trace_printk: Count packets: 1: 4
            ping-618162  [010] ..s21 3651790.136238: bpf_trace_printk: Count packets: 1: 5
            ping-618162  [010] ..s21 3651791.164314: bpf_trace_printk: Count packets: 1: 6
            ping-618162  [010] ..s21 3651792.184385: bpf_trace_printk: Count packets: 1: 7
            ping-618162  [010] ..s21 3651793.208376: bpf_trace_printk: Count packets: 1: 8
            ping-618162  [010] ..s21 3651794.232427: bpf_trace_printk: Count packets: 1: 9
            ping-618162  [010] ..s21 3651795.256482: bpf_trace_printk: Count packets: 1: 10
            ping-618162  [010] ..s21 3651796.280386: bpf_trace_printk: Count packets: 1: 11
```


Anyway, this sample is old and not good.

So if you want to try packet counter, this program is better.
(This is a newer example I made.)
https://github.com/terassyi/seccamp-xdp/blob/main/tutorial/counter_map.bpf.c

To try this, you need to run the following commands.

```console
$ make topology
$ make counter_map.bpf.o
$ make TARGET=counter_map attach
$ sudo bpftool prog tracelog
# You can see output of bpf_printk
# clean up
$ make clean
```

**Comment by terassyi** [comment]
BPF map type is not good and the Go program is also bad.

To implement the packet counter, it is better to use BPF_MAP_TYPE_HASH.
